### ISSUE TITLE
[NumberGuesser] Ругательства

### ISSUE THREAD

**Issue by pavel-b-novikov** [vladlaptevrub/nsudotnet#1]
Должны использовать имя пользователя. И, пожалуйста, не тупой конкатенаций

**Comment by vladlaptevrub** [comment]
Исправлено

**Comment by pavel-b-novikov** [comment]
Нет, не исправлено.

**Comment by vladlaptevrub** [comment]
Разве это неправильно?
Пишу имя и рандомное ругательство без конкатенаций

Console.WriteLine(String.Format("{0}! {1}", name, message[rand.Next(3)]));

**Comment by pavel-b-novikov** [comment]
В середину ругательства имя впихните, блин. Задача - научить вас пользоваться string.Format-ом нормально, чтобы вы познали древнее знание о том, что плейсхолдеры можно сохранять прямо внутри заранее заготовленных строк, которые могут храниться в т.ч. в ресурсах

**Comment by vladlaptevrub** [comment]
Понял вас
Исправлено
