### ISSUE TITLE
[Enigma] Списано?

### ISSUE THREAD

**Issue by pavel-b-novikov** [vladlaptevrub/nsudotnet#4]
Признавайтесь, у кого списали. Я видел похожий код с writealllines и всеми теми же самыми недочетами.

**Comment by vladlaptevrub** [comment]
Для решения задачи спросил у человека, какой подход он использовал для решения (видимо, плохая была идея).
Могу полностью все переделать.

**Comment by pavel-b-novikov** [comment]
Ну вот раз вы списали - вам и искать ошибки в этой задаче. Что я - двойную работу делать буду? Давайте сами ищите ошибку.

**Comment by vladlaptevrub** [comment]
Сделал переименования ( encrypt() => Encrypt(), getAlgorithmName() => GetAlgorithmName() и т.д.)

Разбил класс Enigma на Encryptor и Decryptor, подумал, что Enigma берет много на себя ответственности, выполняя обе функции

**Comment by pavel-b-novikov** [comment]
И все же это не главное

**Comment by vladlaptevrub** [comment]
Исправил следующий момент

было
String keyFilePath = Path.Combine(path, "fikeKey.txt"));

теперь
String keyFilePath = Path.Combine(path, String.Format("{0}.key.txt", inputFile));

до этого все новые ключи записывались в один и тот же файл, что было серьезной ошибкой
для каждого исходного файла нужно создавать уникальный файл с ключом 
иначе ключ потеряем

**Comment by vladlaptevrub** [comment]
еще сравнение строк сделал через Equals

**Comment by pavel-b-novikov** [comment]
Ага, далее?

**Comment by vladlaptevrub** [comment]
это не все?

**Comment by vladlaptevrub** [comment]
еще повторяющийся код можно вынести в отдельный метод
don't repeat yourself и все в этом духе

**Comment by pavel-b-novikov** [comment]
Все равно мимо. Поспрашивайте у сокурсников.

**Comment by vladlaptevrub** [comment]
задиспозил ICryptoTransform

**Comment by pavel-b-novikov** [comment]
наконец-то
