### ISSUE TITLE
[NumberGuesser] Вывод истории

### ISSUE THREAD

**Issue by pavel-b-novikov** [vladlaptevrub/nsudotnet#5]
```
for (var j = 0; j < size; j++)
{
    Console.WriteLine(history.First());
    history.RemoveAt(0);
}
```

Я бы очень хотел знать как надо думать, чтобы до этого додуматься.

**Comment by vladlaptevrub** [comment]
выглядит не очень, согласен
сейчас исправлю

**Comment by vladlaptevrub** [comment]
исправлено
надеюсь, что теперь выглядит поприличнее

**Comment by pavel-b-novikov** [comment]
.ElementAt? А что - мощи индексаторов уже не хватает?

**Comment by vladlaptevrub** [comment]
Теперь делаю так:

 foreach(String line in history)
                    {
                        Console.WriteLine(line);
                    }

**Comment by pavel-b-novikov** [comment]
Отлично, давайте чтобы добить, свернем уже до одной строчки.

**Comment by vladlaptevrub** [comment]
вы про мощь такого индексатора говорили?

for (var j = 0; j < size; j++)
                    {
                        Console.WriteLine(history[j]);
                    }

**Comment by pavel-b-novikov** [comment]
Да. Не используете .ElementAt, если у вас есть в распоряжении индексатор.

**Comment by vladlaptevrub** [comment]
хорошо
исправил и сделал комит

**Comment by pavel-b-novikov** [comment]
Так так, а в одну строчку? Хочу в одну строчку!

**Comment by vladlaptevrub** [comment]
Ваше желание исполнено 

history.ToList().ForEach(Console.WriteLine);

Исправил, залил

**Comment by pavel-b-novikov** [comment]
А ToList вам зачем?

**Comment by vladlaptevrub** [comment]
ступил
у нас и так ведь лист
поторопился
просто нужно hostory.ForEach(Console.WriteLine);

**Comment by vladlaptevrub** [comment]
залил
